export type Filament = {
  id: number;
  color: string;
  material: string;
  brand: string;
  stock: number;
  ordered: number;
  pricePerKg: number;
};

const p = (id:number,color:string,material:string,brand="Bambu",stock=0,pricePerKg=12.5): Filament => ({id,color,material,brand,stock,ordered:0,pricePerKg});

export const initialFilaments: Filament[] = [
  p(1,"Jade-Weiß","PLA Basic","Bambu",3),
  p(2,"Elfenbeinweiß","PLA Matt","Bambu",3),
  p(3,"Knochenweiß","PLA Matt","Bambu",2),
  p(4,"Beige","PLA Basic","Bambu",3),
  p(5,"Champagner","PLA Silk","Bambu",3,17.5),
  p(6,"Wüstenbraun","PLA Matt","Bambu",3),
  p(7,"Milchkaffeebraun","PLA Matt","Bambu",2),
  p(8,"Karamell","PLA Matt","Bambu",3),
  p(9,"Braun","PLA Basic","Bambu",2),
  p(10,"Dunkelbraun","PLA Matt","Bambu",3),
  p(11,"Kakaobraun","PLA Basic","Bambu",3),
  p(12,"Dunkel-Schokoladenbraun","PLA Matt","Bambu",2),
  p(13,"Gold","PLA Silk","iBoss",1,17.5),
  p(14,"Gelb","PLA Basic","Bambu",3),
  p(15,"Zitronengelb","PLA Matt","Bambu",2),
  p(16,"Sonnenblumengelb","PLA Basic","Bambu",2),
  p(17,"Orange","PLA Basic","Bambu",2),
  p(18,"Kürbis-Orange","PLA Basic","Bambu",2),
  p(19,"Mandarin-Orange","PLA Matt","Bambu",1),
  p(20,"Terrakotta","PLA Matt","Bambu",2),
  p(21,"Scharlachrot","PLA Matt","Bambu",2),
  p(22,"Rot","PLA Basic","Bambu",3),
  p(23,"Dunkelrot","PLA Matt","Bambu",2),
  p(24,"Kastanienrot","PLA Basic","Bambu",3),
  p(25,"Kirschrot matt","PLA Matt","Kexcelled",1),
  p(26,"Altrosa","PLA Matt","eSun",0),
  p(27,"Pflaume","PLA Matt","Bambu",2),
  p(28,"Magenta","PLA Basic","Bambu",1),
  p(29,"Heißes Pink","PLA Basic","Bambu",2),
  p(30,"Pink","PLA Basic","Bambu",2),
  p(31,"Sakura-Pink","PLA Matt","Bambu",2),
  p(32,"Flieder-Violett","PLA Matt","Bambu",2),
  p(33,"Lila","PLA Basic","Bambu",2),
  p(34,"Indigo-Violett","PLA Basic","Bambu",2),
  p(35,"Blau-Grau","PLA Basic","Bambu",3),
  p(36,"Eisblau","PLA Matt","Bambu",4),
  p(37,"Himmelblau","PLA Matt","Bambu",1),
  p(38,"Türkis","PLA Basic","Bambu",3),
  p(39,"Cyan","PLA Basic","Bambu",2),
  p(40,"Blau","PLA Basic","Bambu",2),
  p(41,"Kobaltblau","PLA Basic","Bambu",2),
  p(42,"Marineblau","PLA Matt","Bambu",2),
  p(43,"Dunkelblau","PLA Matt","Bambu",3),
  p(44,"Dunkelgrün","PLA Matt","Bambu",2),
  p(45,"Mistelzweig-Grün","PLA Basic","Bambu",1),
  p(46,"Bambusgrün","PLA Basic","Bambu",2),
  p(47,"Grasgrün","PLA Basic","Bambu",2),
  p(48,"Apfelgrün","PLA Matt","Bambu",3),
  p(49,"Hellgrün","PLA Basic","Bambu",2),
  p(50,"Mintgrün","PLA Matt","Overture",0),
  p(51,"Silber","PLA Silk","Bambu",2,17.5),
  p(52,"Hellgrau","PLA Basic","Bambu",2),
  p(53,"Nardo-Grau","PLA Matt","Bambu",2),
  p(54,"Grau","PLA Basic","Bambu",1),
  p(55,"Aschgrau","PLA Matt","Bambu",4),
  p(56,"Dunkelgrau","PLA Basic","Bambu",2),
  p(57,"Schwarz","PLA+","Bambu",0),
  p(58,"Kohlschwarz","PLA Matt","Bambu",2),
  p(59,"Regenbogen","PLA","Unbekannt",0),
  p(60,"Regenbogen matt","PLA Matt","Unbekannt",0),
  p(61,"Gold-Silber-Bronze","PLA","Unbekannt",0),
  p(62,"Rot-Gold-Blau","PLA Silk","EONO",0,17.5),
  p(63,"Rot-Gelb-Blau","PLA Silk","Sunlu",0,17.5),
  p(64,"Blau-Silber","PLA Silk","iBoss",0,17.5),
  p(65,"Marmor","PLA","GIANT ARM",0),
  p(66,"Schwarz-Weiß","PLA+","Sunlu",0),
  p(67,"Schwarz-Gold-Lila","PLA+","Sunlu",0),
  p(68,"Schwarz","PETG","Bambu",0,15),
  p(69,"Weiß","PETG","Bambu",0,15)
];